import{a as d}from"./assets/vendor-B2YOV0tR.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))n(r);new MutationObserver(r=>{for(const o of r)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&n(i)}).observe(document,{childList:!0,subtree:!0});function s(r){const o={};return r.integrity&&(o.integrity=r.integrity),r.referrerPolicy&&(o.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?o.credentials="include":r.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(r){if(r.ep)return;r.ep=!0;const o=s(r);fetch(r.href,o)}})();async function u(t=1,e=8){const s=`https://sound-wave.b.goit.study/api/artists?page=${t}&limit=${e}`;try{const{data:n}=await d.get(s);return n}catch(n){return console.error("Помилка отримання артистів:",n),null}}function f(t){if(!t||!t.strArtistThumb||!t.strArtist||!t.genres||!t.strBiographyEN)return"";const e=t.strBiographyEN.length>200?t.strBiographyEN.slice(0,200)+"...":t.strBiographyEN;return`
        <li class="artist-card">
            <img src="${t.strArtistThumb}" alt="${t.strArtist}" class="artist-image" data-id="${t._id}" />
            <h3 class="artist-name">${t.strArtist}</h3>
            <p class="artist-genre">${t.genres.join(", ")}</p>
            <p class="artist-bio" data-full="${t.strBiographyEN}">${e}</p>
            <button class="learn-more">Learn More</button>
        </li>
    `}const a=document.querySelector(".list-cards"),g=document.getElementById("load-more");let c=1;const m=8;async function l(t=1,e=8){try{const s=await u(t,e);if(!s||!s.artists||!Array.isArray(s.artists))throw new Error("Невірний формат даних: artists відсутній або не є масивом");console.log(`Отримані артисти для сторінки ${t}:`,s.artists),p(s.artists)}catch(s){console.error("Помилка при завантаженні артистів:",s.message)}}function p(t){a.innerHTML="";const e=t.map(f).join("");a.insertAdjacentHTML("beforeend",e)}g.addEventListener("click",()=>{c++,console.log(`Завантажуємо сторінку: ${c}`),l(c,m)});document.addEventListener("click",t=>{if(t.target.classList.contains("learn-more")){const e=t.target.previousElementSibling,s=e.dataset.full;e.classList.contains("expanded")?(e.innerHTML=s.slice(0,200)+"...",t.target.textContent="Learn More"):(e.innerHTML=s,t.target.textContent="Show Less"),e.classList.toggle("expanded")}});l();
//# sourceMappingURL=index.js.map
